### ISSUE TITLE
[v0.11.2] LockingSyncContext not used

### ISSUE THREAD

**Issue by eva-mueller-coremedia** [takari/takari-local-repository#11]
While build with Maven (with `--builder smart`) and using the `takari-local-repository` extension the [LockingSyncContext](https://github.com/takari/takari-local-repository/blob/takari-local-repository-0.11.2/src/main/java/io/takari/aether/concurrency/LockingSyncContext.java) is not used.

How to enable this LockingSyncContext?

This behaviour has been detected while analysing 
[[MRESOLVER-114] ArtifactNotFoundExceptions when building in parallel](https://issues.apache.org/jira/browse/MRESOLVER-114).

**Comment by cstamas** [comment]
This project is being archived, while main features are today provided by Maven Resolver 1.7+, see here https://maven.apache.org/resolver/local-repository.html#shared-access-to-local-repository
