### ISSUE TITLE
[v0.11.2] DefaultFileManager thread safe?

### ISSUE THREAD

**Issue by eva-mueller-coremedia** [takari/takari-local-repository#12]
While analysing [[MRESOLVER-114] ArtifactNotFoundExceptions when building in parallel](https://issues.apache.org/jira/browse/MRESOLVER-114), we 
stumpled upon this [FileLock](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileLock.html) creation: [`raf.getChannel().lock(0, 1, !write);`](https://github.com/takari/takari-local-repository/blob/6784e082fc03987f0e8b7448dcae918629f9ab8a/src/main/java/io/takari/filemanager/internal/DefaultFileManager.java#L380)

The [JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileLock.html) states: "File locks are held on behalf of the entire Java virtual machine. They are not suitable for controlling access to a file by multiple threads within the same virtual machine."

We wondered if the synchronisation will work when building with more than one thread?

Unfortunately we can not verify this due to #11.

**Comment by michael-o** [comment]
This actually does not matter, imho. Please read: https://issues.apache.org/jira/browse/MRESOLVER-132

**Comment by cstamas** [comment]
This project is being archived, while main features are today provided by Maven Resolver 1.7+, see here https://maven.apache.org/resolver/local-repository.html#shared-access-to-local-repository
