### ISSUE TITLE
How to use with maven > 3.6.3

### ISSUE THREAD

**Issue by cconnert** [takari/takari-local-repository#14]
In regards to issue [10](https://github.com/takari/takari-local-repository/issues/10): I followed the guide (http://takari.io/book/30-team-maven.html#installation-and-usage) but did not manage to get takari-local-repository up and running:

- takari-local-repository-0.11.3.jar
- takari-filemanager-0.8.3.jar

Additionally I tried to add takari-smart-builder-0.6.1.jar, but that did not help either. Any input is very appreciated

**Comment by cstamas** [comment]
This project is being archived, while main features are today provided by Maven Resolver 1.7+, see here https://maven.apache.org/resolver/local-repository.html#shared-access-to-local-repository
