### ISSUE TITLE
The process cannot access the file because it is being used by another process(.part.lock)

### ISSUE THREAD

**Issue by J-cztery** [takari/takari-local-repository#4]
I am using maven 3.3.3, takari-filemanager-0.8.3.jar, takari-local-repository-0.11.1.jar on Windows Server 2008 R2. 

There is four mavens running concurrently on an empty local repository and i get
error: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (default) on project sdk: Execution default of goal
org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack failed: Plugin
org.apache.maven.plugins:maven-dependency-plugin:2.8 or one of its
dependencies could not be resolved: Could not transfer artifact
org.apache.maven:maven-artifact-manager:jar:2.0.9 from/to nexus (http://example.com/nexus/content/groups/perth-internal):
C:\Users\Administrator.m2\repository\org\apache\maven\maven-artifact-manager\2.0.9\maven-artifact-manager-2.0.9.jar.part.lock
(The process cannot access the file because it is being used by another
process)

The information with timing is here: 
21:38:57 3>  [INFO] Downloading: http://example.com/nexus/content/groups/perth-internal/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar

21:38:57 1>  [INFO] Downloading: http://example.com/nexus/content/groups/perth-internal/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar

21:38:57 2>  Downloading: http://example.com/nexus/content/groups/perth-internal/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar

21:38:57 4>  [INFO] Downloading: http://example.com/nexus/content/groups/perth-internal/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar

21:38:58 3>  [INFO] Downloaded: http://example.com/nexus/content/groups/perth-internal/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar (57 KB at 17.6 KB/sec)

21:38:58 2>  Downloaded: http://example.com/nexus/content/groups/perth-internal/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar (0 B at 0.0 KB/sec)

21:38:59 1>  [INFO] Downloaded: http://example.com/nexus/content/groups/perth-internal/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.jar (0 B at 0.0 KB/sec)

21:39:06 4>  [INFO] ------------------------------------------------------------------------
21:39:06 4>  [INFO] BUILD FAILURE
21:39:06 4>  [INFO] ------------------------------------------------------------------------
21:39:06 4>  [INFO] Total time: 03:03 min
21:39:06 4>  [INFO] Finished at: 2015-05-23T21:39:06+08:00
21:39:06 4>  [INFO] Final Memory: 9M/61M
21:39:06 4>  [INFO] ------------------------------------------------------------------------
21:39:06 4>  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (default) on project sdk: Execution default of goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.8 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-artifact-manager:jar:2.0.9 from/to nexus (http://example.com/nexus/content/groups/perth-internal): C:\Users\Administrator.m2\repository\org\apache\maven\maven-artifact-manager\2.0.9\maven-artifact-manager-2.0.9.jar.part.lock (The process cannot access the file because it is being used by another process) -> 

Note, that i changed the real url to example.com

**Comment by ifedorenko** [comment]
Maybe worth to run the build with -e parameter, so maven prints full exception stack trace, not just the message.

**Comment by J-cztery** [comment]
Here is log from the same project run with mvn -X (I hope it does the same thing as -e plus additional logs) http://filebin.ca/22mrv4vOfCuM/DEBUG_2.zip

**Comment by J-cztery** [comment]
BTW: is what i am doing supported? I mean just dropping takari-filemanager-0.8.3.jar, takari-local-repository-0.11.1.jar into lib/ext directory of maven and not TEAM installation?

**Comment by jvanzyl** [comment]
Yes. I've not seen this type of interference with the .lock files produced by Aether for dealing with partial downloads.

**Comment by ifedorenko** [comment]
Out of curiosity, how did you get multiple builds output to the same log file?

**Comment by J-cztery** [comment]
Visual Studio/msbuild is that smart. The timestamping is added by Jenkins' plugin. We have C++ projects which run custom actions on pom.xml files to trigger maven. Msbuild runs the projects in parallel using 4 threads.

**Comment by J-cztery** [comment]
Hi, Any news on this one? Do you need some more information?

**Comment by jvanzyl** [comment]
Can you test if you get the same issue not using our local repository? As that file is specifically an either file. So if it works without our local repository implementation then it's likely an interaction issue with our implementation and Aether.

**Comment by J-cztery** [comment]
I can and will do it ASAP. But the problem is that your implementation of local repository is supposed to be thread and executions safe, the other one does not promise this. So even if it fails it is allowed to do so.

**Comment by seanf** [comment]
FWIW, I saw that same error "....jar.part.lock (Access is denied)" on Windows 10 when running the multi-threaded, single-process, aether-based test from https://github.com/ifedorenko/takari-local-repository-race with the *standard* repository code (I commented out takari-local-repository in the pom). I suppose that makes it a bug in Aether.

**Comment by tizki** [comment]
hi
any update about this issue?
thanks

**Comment by cstamas** [comment]
This project is being archived, while main features are today provided by Maven Resolver 1.7+, see here https://maven.apache.org/resolver/local-repository.html#shared-access-to-local-repository
