### ISSUE TITLE
apparent race during maven multi-threaded build

### ISSUE THREAD

**Issue by ifedorenko** [takari/takari-local-repository#5]
Use of takari-local-repository results in spurious artifact resolution errors during multi-threaded maven build that resolves dependencies from several remote repositories. I've setup simple stress test that demonstrates the problem at https://github.com/ifedorenko/takari-local-repository-race

**Comment by tizki** [comment]
hi
any update about this issue?
thanks

**Comment by ifedorenko** [comment]
There are currently no plans to work on this issue. From our experience, default Aether local repository implementation works well-enough in multithreaded builds, at least on OSX and Linux, if you disable resumable downloads.
